# Enables you to specify a file where Kibana stores log output.
logging:
  appenders:
    file:
      type: file
      fileName: /var/log/kibana/kibana.log
      layout:
        type: json
  root:
    appenders:
      - default
      - file
# Specifies the path where Kibana creates the process ID file.
pid.file: /run/kibana/kibana.pid
